---
- name: create_groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items:
    - "{{ var_groups }}"
  ignore_errors: true
  become: true

- name: check_register_sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ item.name }}(.*)"
    line: "^%{{ item.name }} {{ item.sudoers_define }}"
  with_items: 
    - "{{ var_groups }}"
  when: 
    - enable_register_sudoers is "True"
    - item.sudoers_define is defined
  become: true
  ignore_errors: true