---
- name: create_groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items:
    - "{{ var_groups }}"
  ignore_errors: true
  become: true

- name: register_sudoers
  command: "echo {{ item.name }}  {{ item.sudoers_define }} >> /etc/sudoers"
  with_items: "{{ var_groups }}"
  when: 
    - enable_register_sudoers is "True"
    - item.sudoers_define is define