---
- name: create_groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items:
    - "{{ var_groups }}"
  ignore_errors: true
  become: true

- name: check_register_sudoers
  command: 'echo "%{{ item.name }} {{ item.sudoers_define }}" > /etc/sudoers.d/{{item.name}}'
  with_items: 
    - "{{ var_groups }}"
  become: true
  ignore_errors: true