---
- name : check install httpd to webservers
  hosts: webservers
  tasks:
    - name: check installed httpd
      yum: 
        name: httpd
        state: installed
      check_mode: true
      register: result_httpd_installed

    - name: assert httpd installed
      assert:
        that:
          - result_yum_installed.changed is false