---
- name: check installed httpd
  yum: 
    name: httpd
    state: installed

- name: copy config-file to remote
  become: true
  copy: 
    src: 'httpd.conf'
    dest: '/etc/httpd/conf/httpd.conf'
    owner: 'root'
    mode: 644
    force: true
  notify: httpd_restart

