---
- hosts: 'linux'
  gather_facts: true
  roles:
    - role: RHEL/yum_update
    - role: RHEL/yum_extra_install
      var_yum_extra_install: "True"
      yum_extra_installed:
        - "traceroute"
        - "nmap"
    - role: RHEL/disable_selinux
      var_selinux_state: "disabled"
      var_selinux_policy: "targeted"
    - role: RHEL/grub_setting
    - role: RHEL/pwquality_conf
    - role: RHEL/chrony_conf
  strategy: free

- hosts: 'windows'
  gather_facts: true
  roles:
    - role: windows/add_user
  strategy: free


- hosts: 'webservers'
  gather_facts: false
  roles: 
    - role: RHEL/httpd_service
      VARS_LISTNER: '10080'
  strategy: free

- hosts: 'appservers'
  gather_facts: false
  roles:
    - role: RHEL/jdk_service
  strategy: free
