---
- hosts: 'linux'
  gather_facts: true
  roles:
    - role: RHEL/disable_service
      disable_service_names: 
        - { name: postfix.service }
    - role: RHEL/yum_update
    - role: RHEL/manage_yum_repository
      var_add_yum_repository:  
        - {name: test ,url: "https://download.docker.com/linux/centos/docker-ce.repo" ,description: "docekr-ce"}

  strategy: free

- hosts: 'windows'
  gather_facts: true
  roles:
    - role: windows/add_user
  strategy: free


- hosts: 'webservers'
  gather_facts: false
  roles: 
    - role: RHEL/httpd_service
      VARS_LISTNER: '10080'
  strategy: free

- hosts: 'appservers'
  gather_facts: false
  roles:
    - role: RHEL/jdk_service
  strategy: free
