---
- hosts: 'linux'
  gather_facts: true
  roles:
    - role: RHEL/yum_update
    - role: RHEL/yum_extra_install
      var_yum_extra_install: "True"
      yum_extra_installed:
        - "traceroute"
        - "nmap"
    - role: RHEL/disable_selinux
      var_selinux_state: "disabled"
      var_selinux_policy: "targeted"
#    - role: RHEL/grub_setting
    - role: RHEL/pwquality_conf
    - role: RHEL/chrony_conf
    - role: RHEL/audit_rules
    - role: RHEL/disable_service
    - role: RHEL/group_manage
      enable_register_sudoers: True
      var_groups:
      - { name: "testgroup", gid: 1100 , sudoers_define: "ALL=(ALL) NOPASSWD:ALL" }
    - role: RHEL/user_manage
      enable_register_sudoers: False
      var_users: 
      - { name: "testuser1", uid: 1101, group: "testgroup"}
      - { name: "testuser2", uid: 1102, group: "testgroup"}
      - { name: "testuser3", uid: 1103, group: "testgroup"}
  strategy: free

- hosts: 'windows'
  gather_facts: true
  roles:
    - role: windows/add_user
  strategy: free


- hosts: 'webservers'
  gather_facts: false
  roles: 
    - role: RHEL/httpd_service
      VARS_LISTNER: '10080'
  strategy: free

- hosts: 'appservers'
  gather_facts: false
  roles:
    - role: RHEL/jdk_service
  strategy: free
