---
- name: create_user with id
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    uid: "{{ item.uid }}"
    state: present
  with_items:
    - "{{ var_users }}"
  ignore_errors: true
  become: true


