---
- name: create_user with id
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    uid: "{{ item.uid }}"
    state: present
  with_items:
    - "{{ var_users }}"
  ignore_errors: true
  become: true


- name: check_register_sudoers
  lineinfile: 
    path: /etc/sudoers
    line: "{{ item.name }} {{ item.sudoers_define }}" 
    regexp: "^{{ item.name }}"
    state: present
  with_items: 
    - "{{ var_users }}"
  become: true
  ignore_errors: true